### ISSUE TITLE
Improve ESR pictures

### ISSUE THREAD

**Issue by iquito** [ravage84/SwissPaymentSlip#28]
The pictures used in the library are not ideal (especially the colors and contrast) and a version without a bank is missing. Postfinance has better ones available on their website in PDF format. If somebody is interested in implementing them or if you are searching for them (because it took me quite some time to find them), they can be found here:

https://www.postfinance.ch/de/cust/download/bizdoc.html

I have also created a drop-in replacement of the orange ESR gif specifically without bank:

![esr_ohne_bank](https://cloud.githubusercontent.com/assets/973653/22222438/1aa0546a-e1b7-11e6-941b-29c76ebd41a3.gif)

If somebody wants to use it, this is how (with this class and the new gif in the same directory):

    use SwissPaymentSlip\SwissPaymentSlip\OrangePaymentSlip;
    
    class ImprovedOrangePaymentSlip extends OrangePaymentSlip
    {
      /**
       * Sets the default attributes of the elements for an orange slip
       *
       * @return $this The current instance for a fluent interface.
       */
      protected function setDefaults()
      {
        parent::setDefaults();

        $this->setSlipBackground(__DIR__.'/esr_ohne_bank.gif');

        $this->setRecipientLeftAttr(3, 15, 50, 4);
        $this->setRecipientRightAttr(66, 15, 50, 4);

        return $this;
      }
    }

**Comment by ravage84** [comment]
@iquito  thanks for your feedback.

I used the existing picture because it was once added to the original library I based my work on.
I'm not sure what the license of the picture is, which the Postfinance provides, so I was reluctant to include it.

I never took the additional mile to get in touch with them about that, but if anybody wants to do that and get some insight on the license or get a exclusive permission to use it in this library, I'm willing to include it.
