### ISSUE TITLE
Wrong return value in getAmountCents()

### ISSUE THREAD

**Issue by Saneke** [ravage84/SwissPaymentSlip#43]
I have set 2714.05 with setAmount(). 
In the return value from function $paymentSlipData->getAmountCents() it is 
2714.50. 

The bug is in the code line 840 in PaymentSlipData.php

`$ret = str_pad($cents, 2, '0', STR_PAD_RIGHT);`

STR_PAD_RIGHT should be STR_PAD_LEFT then it works correctly.

**Comment by ravage84** [comment]
@Saneke thank you for your bug report. This sounds very much like @7, which was fixed by #21 and released as version 0.12.1.
So, it [should work](https://github.com/ravage84/SwissPaymentSlip/blob/3f5e23552e59ff486318c3af66b0374fa61a176f/src/PaymentSlipData.php#L840). Can you check your version, please?
